site_name: Synalinks
site_url: https://synalinks.github.io/synalinks
repo_url: https://github.com/SynaLinks/synalinks
repo_name: SynaLinks/synalinks
theme:
  name: material
  logo: assets/synalinks_logo.png
  favicon: assets/synalinks_favicon.png
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - glightbox

nav:
  - index.md
  - Introduction.md
  - FAQ.md
  - Code Examples:
    - Basics:
      - Code Examples/Basics/First Steps.md
      - Code Examples/Basics/First Programs.md
      - Code Examples/Basics/Control Flow.md
      - Code Examples/Basics/Conversational Applications.md
      - Code Examples/Basics/Reward Metrics And Optimizers.md
      - Code Examples/Basics/Training Programs.md
    - Advanced:
      - Code Examples/Advanced/Implementing Custom Modules And Programs Via Subclassing.md
      - Code Examples/Advanced/First Knowledge Graph Schema.md
      - Code Examples/Advanced/Knowledge Extraction.md
      - Code Examples/Advanced/Retrieval Augmented Generation.md
      - Code Examples/Advanced/Knowledge Augmented Generation.md
  - Synalinks API:
    - Synalinks API/Language Models API.md
    - Synalinks API/Embedding Models API.md
    - Synalinks API/Knowledge Bases API.md
    - Data Models API:
      - Synalinks API/Data Models API/index.md
      - Synalinks API/Data Models API/The DataModel class.md
      - Synalinks API/Data Models API/The JsonDataModel class.md
      - Synalinks API/Data Models API/The SymbolicDataModel class.md
      - Synalinks API/Data Models API/The Variable class.md
      - Synalinks API/Data Models API/The Base DataModels.md
    - Programs API:
      - Synalinks API/Programs API/index.md
      - Synalinks API/Programs API/The Program class.md
      - Synalinks API/Programs API/The Sequential class.md
      - Synalinks API/Programs API/Program training API.md
      - Program Saving API:
        - Synalinks API/Programs API/Program Saving API/Program saving and loading.md
        - Synalinks API/Programs API/Program Saving API/Variable saving and loading.md
    - Modules API:
      - Synalinks API/Modules API/index.md
      - Synalinks API/Modules API/Base Module class.md
      - Core Modules:
        - Synalinks API/Modules API/Core Modules/index.md
        - Synalinks API/Modules API/Core Modules/Input module.md
        - Synalinks API/Modules API/Core Modules/Identity module.md
        - Synalinks API/Modules API/Core Modules/Not module.md
        - Synalinks API/Modules API/Core Modules/Generator module.md
        - Synalinks API/Modules API/Core Modules/Decision module.md
        - Synalinks API/Modules API/Core Modules/Action module.md
        - Synalinks API/Modules API/Core Modules/Branch module.md
      - Knowledge Modules:
        - Synalinks API/Modules API/Knowledge Modules/index.md
        - Synalinks API/Modules API/Knowledge Modules/Embedding module.md
        - Synalinks API/Modules API/Knowledge Modules/UpdateKnowledge module.md
        - Synalinks API/Modules API/Knowledge Modules/EntityRetriever module.md
        - Synalinks API/Modules API/Knowledge Modules/KnowledgeRetriever module.md
      - Merging Modules:
        - Synalinks API/Modules API/Merging Modules/index.md
        - Synalinks API/Modules API/Merging Modules/Concat module.md
        - Synalinks API/Modules API/Merging Modules/And module.md
        - Synalinks API/Modules API/Merging Modules/Or module.md
        - Synalinks API/Modules API/Merging Modules/Xor module.md
      - Test Time Compute Modules:
        - Synalinks API/Modules API/Test Time Compute Modules/index.md
        - Synalinks API/Modules API/Test Time Compute Modules/ChainOfThought module.md
        - Synalinks API/Modules API/Test Time Compute Modules/SelfCritique module.md
      - Agents Modules:
        - Synalinks API/Modules API/Agents Modules/index.md
        - Synalinks API/Modules API/Agents Modules/ReACT Agent module.md
        - Synalinks API/Modules API/Agents Modules/Parallel ReACT Agent module.md
    - Callbacks API:
      - Synalinks API/Callbacks API/index.md
      - Synalinks API/Callbacks API/Base Callback class.md
      - Synalinks API/Callbacks API/ProgramCheckpoint.md
      - Synalinks API/Callbacks API/CSVLogger.md
    - Ops API:
      - Synalinks API/Ops API/index.md
      - Synalinks API/Ops API/JSON Ops.md
      - Synalinks API/Ops API/Language Models Ops.md
      - Synalinks API/Ops API/Embedding Models Ops.md
    - Optimizers API:
      - Synalinks API/Optimizers API/index.md
      - Synalinks API/Optimizers API/Base Optimizer class.md
      - Synalinks API/Optimizers API/RandomFewShot.md
      - Synalinks API/Optimizers API/OPRO.md
      - Synalinks API/Optimizers API/FewShotOPRO.md
    - Metrics:
      - Synalinks API/Metrics/index.md
      - Synalinks API/Metrics/Base Metric class.md
      - Synalinks API/Metrics/Metric wrappers and reduction metrics.md
      - Synalinks API/Metrics/Regression metrics.md
      - Synalinks API/Metrics/FScore metrics.md
    - Rewards:
      - Synalinks API/Rewards/index.md
      - Synalinks API/Rewards/ExactMatch reward.md
      - Synalinks API/Rewards/CosineSimilarity reward.md
      - Synalinks API/Rewards/LMAsJudge reward.md
      - Synalinks API/Rewards/Reward wrappers.md
    - Built-in Datasets:
      - Synalinks API/Built-in Datasets/index.md
      - Synalinks API/Built-in Datasets/GSM8K.md
      - Synalinks API/Built-in Datasets/HotpotQA.md
      - Synalinks API/Built-in Datasets/ARC-AGI.md
    - Utilities:
      - Synalinks API/Utilities/Program plotting utilities.md
      - Synalinks API/Utilities/More plotting utilities.md
      - Synalinks API/Utilities/NLP utilities.md
    - Synalinks API/Config.md
  - Deployment:
    - Deployment/Building a REST API.md
  - Graph Visualization:
    - Graph Visualization/Using G.V() as Graph IDE.md
  - Monitoring:
    - Monitoring/Arize Phoenix.md